### ISSUE TITLE
HowTo: Style Dates

### ISSUE THREAD

**Issue by benrudhart** [AllanJuenemann/CalendarView#6]
Hi @AllanJuenemann,

I'm wondering if there is a way to style the dates in the calendar view, i.e. not a decoration view below the dates.
E.g. like a colored background (circle/ square etc) behind the day number itself.
Thank you.

**Comment by AllanJuenemann** [comment]
I agree, that would be really nice. Unfortunately, [UICalendarView](https://developer.apple.com/documentation/uikit/uicalendarview) doesn't provide that option yet. Decorations are the closest we have to visual customization.

`CalendarView` is really just meant to be a SwiftUI wrapper for UIKit's `UICalendarView`. Anything beyond what's provided by `UICalendarView` would require a custom implementation.

**Comment by benrudhart** [comment]
I see, thank you!
